import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const eucliCircular = localFont({
  src: [
    {
      path: "./fonts/EuclidCircularB-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/EuclidCircularB-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/EuclidCircularB-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/EuclidCircularB-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-eucli-circular",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${eucliCircular.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
